"""Initial migration.

Revision ID: 8ef0c24a25ff
Revises: 
Create Date: 2023-02-10 17:16:10.967441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef0c24a25ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('employment_status', sa.String(length=50), nullable=False),
    sa.Column('loan_history', sa.String(length=100), nullable=False),
    sa.Column('bank_account_info', sa.String(length=100), nullable=False),
    sa.Column('government_issued_id', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('education', sa.String(length=100), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.Column('marital_status', sa.String(length=50), nullable=False),
    sa.Column('spending_habits', sa.String(length=100), nullable=False),
    sa.Column('payment_history', sa.String(length=100), nullable=False),
    sa.Column('transaction_frequency', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_profile')
    # ### end Alembic commands ###
